parameters:
    summercamp.export.controller.class: EzSystems\SummerCamp2013PublicApiBundle\Controller\ExportController

services:
    summercamp.export.controller:
        class: %summercamp.export.controller.class%
        calls:
            - [ setContainer, [@service_container] ]
