parameters:
#    ez_systems_summer_camp2013_public_api.example.class: EzSystems\SummerCamp2013PublicApiBundle\Example

services:
#    ez_systems_summer_camp2013_public_api.example:
#        class: %ez_systems_summer_camp2013_public_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
